//DROP TABLE BUMON_TBL;

DROP TABLE IF EXISTS BUMON_TBL;
CREATE TABLE BUMON_TBL(
	BUMON_CD CHAR(3),
	BUMON_NM VARCHAR2(20),
	PRIMARY KEY(BUMON_CD)
	);
	
DROP TABLE IF EXISTS SHAIN_TBL;
CREATE TABLE IF NOT EXISTS SHAIN_TBL(
	SHAIN_CD CHAR(5),
	SHAIN_NM VARCHAR2(30),
	BUMON_CD CHAR(3),
	KANRI_CD CHAR(3),
	JYUSHO VARCHAR2(60),
	DENWA CHAR(10),
	SEIBETSU CHAR(1),
	NYUSHA_DATE CHAR(8),
	NENREI NUMBER(3),
	YAKUSHOKU_CD CHAR(4),
	KYURYO NUMBER(7),
	JYOCHO_CD CHAR(5),
	TAISHOKU_DATE CHAR(8),
	PRIMARY KEY(SHAIN_CD)
	);
